version: "2.2"

services:
  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=helloworld
      - POSTGRES_USER=postgres
      - POSTGRES_DB=university
#    profiles:
#      - postgres